[package]
name = "KanariLibrary"
version = "1.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/move-stdlib", rev = "13f4dc0" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/moveos-stdlib", rev = "13f4dc0" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/rooch-framework", rev = "13f4dc0" }

[addresses]
kanari_library = "0x6"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
